section Clinical
color red

thread FiH
Cohort 1: 1-Mar-24 - 1-Apr-24
SMC 1: 15-Apr-24
Cohort 2: 21-Apr-24 - 21-May-24
SMC 2: 31-May-24
Cohort 3a: 5-Jun-24 - 5-Jul-24
SMC 3: 18-Jul-24
SMC 4: 1-Aug-24
wrong: 1-Oct-24 - 1-Sep-24

thread study 2
FSI: 1-Aug-2024
FSFD: 15-Aug-24
Interim analysis: 15-2-25
conduct: 15-Aug-2024 - 30-Sep-25
IDMC1: 30-Sep-24
IDMC2: 1-Dec-24



section Regulatory
color blue
# comment

thread FDA interaction

Briefing Book draft 1: 15-Jun-2024
BB review 1: 16-Jun-24 - 30-6-24
BB draft 2:   1-Jul-24
BB submission: 15.7.24 

thread Submission
Start: 1-Mar-2024
Dossier final: 31-Aug-2024