MARKER 15-Nov-2024

section Clinical (color: red)
#color red

thread study 1
Cohort 1: 1-Mar-24 - 1-Apr (fill: red)
SMC 1: 15-Apr
Cohort 2: 21-Apr - 21-May
SMC 2: 31-5
Cohort 3a: 5-Jun-24 - 5-Jul-24
SMC 3: 18-Jul-24 (color: red, fill: red)
SMC 4: 1-Aug-24
#wrong: 1-Oct-24 - 1-Sep-24 

thread study 2
FSI: 1-Aug-2024
FSFD: 15-Aug-24
Interim analysis: 15-2-25
conduct: 15-Aug-2024 - 30-Sep-25 (color: red)
IDMC1: 30-Sep-24
IDMC2: 1-Dec-24

thread study 3
shell: 1-Aug - 7-Aug
draft 1: 7-Aug - 14-Aug
CRM: 14-Aug
draft 2: 14-Aug - 21-Aug
final: 21-Aug
manuscript draft 1: 1-Jan-25 - 5-Jan-25
manuscript draft 2: 5-Jan - 21-Jan

section Regulatory (color: blue)
#color blue
# comment

thread FDA interaction

Briefing Book draft 1: 15-Jun-2024
BB review 1: 16-Jun-24 - 30-6-24
BB draft 2:   1-Jul-24
BB submission: 15.7.24 

thread Submission
Start: 1-Mar-2024
Dossier final: 31-Aug-2024
a very long label: 1-Sep-2025

THREAD spacing test
A: 1-Feb-25
B: 1-Mar-25
AB: 1-2 - 1-3

CC: 1-5 - 1-6
DD: 1-6 - 1-7
EE: 1-7 - 1-8

C: 1-6
D: 1-7

FF: 1-7-24 - 1-8
GG: 1-8 - 1-9
HH: 1-9 - 15-9
II: 15-9 - 22-9
JJ: 22-9 - 24-9
KK: 24-9 - 26-9
L: 30-9

MM: 1-12 - 31-12
N: 7-12
O: 10-12
P: 22-12